AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hamza-devops-site-987654   # tamamen unique
      WebsiteConfiguration:
        IndexDocument: index.html

  BucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref MyBucket
    PolicyDocument:
      Statement:
        - Effect: Allow
          Principal: "*"
          Action: "s3:GetObject"
          Resource: !Sub "${MyBucket}/*"
Outputs:
  WebsiteURL:
    Value: !GetAtt MyBucket.WebsiteURL
