AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hamza-devops-site-984321
      WebsiteConfiguration:
        IndexDocument: index.html

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${MyBucket}/*"

Outputs:
  WebsiteURL:
    Value: !GetAtt MyBucket.WebsiteURL
  BucketName:
    Value: !Ref MyBucket
