AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hamza-devops-site-987654321
      WebsiteConfiguration:
        IndexDocument: index.html

Outputs:
  WebsiteURL:
    Value: !GetAtt MyBucket.WebsiteURL
